version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.9.4
        environment:
          MIX_ENV: test
      - image: circleci/postgres:10.1-alpine
        environment:
          PG_USER: postgres
          PG_PASSWORD: app_test
    working_directory: ~/app
    steps:
      - checkout
      - run: mix local.hex --force
      - run: mix local.rebar --force
      - restore_cache:
          keys:
            - v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
            - v1-mix-cache-{{ .Branch }}
            - v1-mix-cache
      - restore_cache:
          keys:
            - v1-build-cache-{{ .Branch }}
            - v1-build-cache
      - run: mix do deps.get, deps.compile, compile --warnings-as-errors

      - run: mix dialyzer

      - save_cache:
          key: v1-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache-{{ .Branch }}
          paths: "deps"
      - save_cache:
          key: v1-mix-cache
          paths: "deps"
      - save_cache:
          key: v1-build-cache-{{ .Branch }}
          paths: "_build"
      - save_cache:
          key: v1-build-cache
          paths: "_build"

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run credo tests
          command: mix credo -a --strict --ignore todo

      - run: mix test

      - store_test_results:
          path: _build/test/lib/banking

      - run:
          name: check test coverage
          command: mix coveralls && mix coveralls.post -t $COVERALLS_REPO_TOKEN  -b ${CIRCLE_BRANCH} -m "`git log -1 --pretty=%B`" -n circleci -c "`git log -1 --pretty=format:'%an'`"
